# Generated by Django 4.2 on 2023-04-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Scopes',
        ),
    ]
