# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 024cdc9e8decf6222067549a6b4b83ae9dc9094e

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/24/
Content-Type: application/json
Authorization: Token 76bf5cb5fca21c8126fafeb3435c55e11a03e6e1

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-04-5
Content-Type: application/json

###
#удаление
DELETE {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token 024cdc9e8decf6222067549a6b4b83ae9dc9094e